### ISSUE TITLE
'default language' device setting not documented

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#100]
![image](https://user-images.githubusercontent.com/2367265/59353384-dbd94600-8cf0-11e9-9d7a-1239bf621079.png)

see thread here: 
https://learningequality.slack.com/archives/CAVFL3J67/p1560318556014600

cc @radinamatic @cpauya @mrpau-julius

**Comment by radinamatic** [comment]
My bad for completely forgetting about this feature... :disappointed: 

However, now that I set off to finally document it, I'm unsure what new it brings compared to the language switcher in the user menu, and even how it is supposed to work...?

Feature description says `The changes you make here will affect this device only.`, and as I recall, this is meant to notify of the limitation that it will not affect the Kolibri UI interface on *client devices*. However, when language is changed under _Selected_, confirmation notification is there, but the UI language remains the same even when the page is reloaded.

If the user then changes something in the language switcher, that one does the trick, but the value in the _Selected_ field remains the same which makes it completely confusing... :confused: 

![default-language](https://user-images.githubusercontent.com/1457929/59373231-88dfad00-8d49-11e9-942c-340c50c48ce4.gif)

cc @indirectlylit @rtibbles @khangmach

**Comment by indirectlylit** [comment]
> My bad for completely forgetting about this feature... 😞

no worries - the label was missing from https://github.com/learningequality/kolibri/pull/5251

My understanding is that the intended behavior is that language precedence is determined by:

1. user-selected language (highest priority)
2. device setting default language

So a device admin will use this setting to set what language new users see by default when they log into a facility on this device. If a user (including the device admin) sets a language preference for themselves, that overrides the device default.

The warning about "this device only" is confusing. It's probably intended to mean that the default language doesn't propagate/sync with the facility to other servers. It is not intended to refer to "client devices"

**Comment by radinamatic** [comment]
> 1. user-selected language (highest priority)

"User-selected language" **where** exactly: browser default language...? Kolibri selected language? What counts as "selected" language: the fact that a user different from device admin opens the sign-in page (let's say admin's default is in English), and signs in without selecting any other language? Does that mean that the user "accepted" English as the (default) selected?

Still failing to understand how is this supposed to work - I tried and failed to make any change in this option that would be visible to other users (using incognito sessions, or different browsers, creating new users to get to some kind of "default" or "not-selected" state...)

`needs user docs` label is not the only one missing in that PR,  apparently `needs gherkin scenario` is much more dire.
