### ISSUE TITLE
orphan 'tutorials' link visible in TOC

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#103]
At some point recently, the orphan 'tutorials' link snuck back into the TOC:

| latest | 0.11 |
|--|--|
|![image](https://user-images.githubusercontent.com/2367265/59637720-805dec80-9124-11e9-8222-a6894acfb495.png) | ![image](https://user-images.githubusercontent.com/2367265/59637735-894ebe00-9124-11e9-9d15-770fe189f7f9.png) |

refs:

* https://github.com/learningequality/kolibri-docs/pull/52
* https://github.com/learningequality/kolibri-docs/issues/60

**Comment by radinamatic** [comment]
Apparently the `:orphan:` directive you suggested was never implemented...?

Will add in the following update! :+1:

**Comment by radinamatic** [comment]
Fixed in #105, closing!
