### ISSUE TITLE
update raspberry pi tutorial to use kolibri-server package

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#104]
The [Debian/Ubuntu section](https://kolibri.readthedocs.io/en/latest/install.html#kolibri-server-pre-release) says that

>  Typical use case would be a Raspberry Pi 3+ device with 4 CPU cores, which will perform much better and faster with kolibri-server compared to base Kolibri.

However the [RPi tutorial](https://kolibri.readthedocs.io/en/latest/install/tutorials/rpi.html) contains manual NGINX configuration instructions and does not mention `kolibri-server`.

**Comment by indirectlylit** [comment]
refs: https://github.com/learningequality/kolibri-docs/pull/52#pullrequestreview-208671830

**Comment by benjaoming** [comment]
Yes, we need to change this. The tutorial was written before `kolibri-server` was made.

**Comment by radinamatic** [comment]
@benjaoming Could you take this on and update the RPi tutorial?

**Comment by benjaoming** [comment]
It's been in my TODO for a few weeks :sob:

**Comment by radinamatic** [comment]
Fixed in #118
