### ISSUE TITLE
update guidance on running kolibri.exe from command line

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#107]
Pending https://github.com/learningequality/kolibri-installer-windows/issues/102

Once `kolibri.exe` is available from the system path, we can simplify the instructions, removing references to `C:/PythonXY/Scripts`

**Comment by radinamatic** [comment]
That will be a great addition, and so much help! :+1:

**Comment by cpauya** [comment]
https://github.com/learningequality/kolibri-installer-windows/issues/102 was already merged.

We can already work on this to be included in v0.12.6 😸

**Comment by radinamatic** [comment]
Fixed in #116
