### ISSUE TITLE
kolibri-server is not easily found in TOC

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#108]
The `kolibri-server` section is not easily found in the table of contents because of the deep nesting:

![image](https://user-images.githubusercontent.com/2367265/60465727-aa281080-9c06-11e9-864c-76fe34015a09.png)

https://kolibri.readthedocs.io/en/latest/install.html#kolibri-server-pre-release

Recommend making the heading one level higher, so it's a direct child of Debian/Ubuntu

**Comment by radinamatic** [comment]
True, it's a legacy from the time when it was not yet officially released. Will amend asap! 👍

**Comment by benjaoming** [comment]
Proposing also a renaming of the heading to something like "Classroom server". When we called the package `kolibri-server`, it was with an understanding that it would easily create confusion.

Of course, since it's still for Debian/Ubuntu, it's a great idea to keep it there.

**Comment by indirectlylit** [comment]
Maybe call it "Server package"?

> Proposing also a renaming of the heading to something like "Classroom server".

I really disagree with this: you can run Kolibri as a "classroom server" without the `kolibri-server` Debian package, and you can use the `kolibri-server` Debian package as something that's not in a classroom. The two ideas are independent.

> When we called the package kolibri-server, it was with an understanding that it would easily create confusion.

Do you have a reference for this? As far as I can tell, all our conversations landed on `kolibri-server` being the least-objectionable option. References:

* https://docs.google.com/document/d/1tkUCgYwTJPro2mMLMDX-BSIGo59ynAUBTZAxzSibKJI/edit
* https://learningequality.slack.com/archives/CAWKSU7KR/p1547654611017400
