### ISSUE TITLE
hardware requirements should be distinct for Windows and Linux

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#115]
Current [server requirements](https://kolibri.readthedocs.io/en/latest/install.html#servers):

> ![image](https://user-images.githubusercontent.com/2367265/61737890-fa921a00-ad3d-11e9-8758-f38256f0ea71.png)

@jredrejo notes that:

> I think we should have different requirements on Windows and Linux. On Linux you can run it with 1 GB of RAM but I doubt you can even boot a Windows 10 with just that amount of memory.

**Comment by radinamatic** [comment]
Agreed, I'll add a note that Windows devices will need at least 2GB.

**Comment by radinamatic** [comment]
Fixed in #116
