### ISSUE TITLE
add information about running Kolibri in an NComputing environment

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#126]
we've had a couple instances now of people using [NComputing setups](https://www.ncomputing.com/products/vSpace/vSpace%20PRO) and running into problems.

ref: https://learningequality.slack.com/archives/C0LKF6TRD/p1566499868052700

from @jamalex 

> if you set the Kolibri windows installer to autostart Kolibri at boot, it does so for every account. Every terminal on an n-computing cluster is a new account --  it's all the same computer (one IP -- and same 127.0.0.1), but different home directories depending on who logged in first.
> 
> So it should be disabled from autostarting on every account except the main admin account, and then the teacher needs to log in using that account after the computer is turned on to start kolibri up
> 
> Installing Kolibri also put the Kolibri launcher icon on the desktop of every student account so we removed those and instead added a URL shortcut icon

We should update the docs to give people this info

**Comment by radinamatic** [comment]
Fixed in #128
