### ISSUE TITLE
document any best practices related to upgrading and trying new versions and installation methods

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#148]
We've observed some issues related to trying new versions and installation methods. One example:  https://github.com/learningequality/kolibri/issues/6388

There are likely many other examples. Let's try brainstorm and document some best practices to avoid situations that we expect might cause issues.

**Comment by radinamatic** [comment]
@indirectlylit from the above learningequality/kolibri#6388 I'm not seeing what would be the appropriate recommendation to add to the docs for the upgrade section :thinking:

**Comment by indirectlylit** [comment]
no, it's not clear to me either. At a minimum though, we can say "make sure to shut down Kolibri before upgrading"

**Comment by benjaoming** [comment]
Can we safeguard some of this in the code, rather than through documentation?

**Comment by radinamatic** [comment]
I've added warnings in the docs, but ideally yes, this should be implemented in the installer. 
On Windows at least, the installer does stop the server before proceeding.

**Comment by radinamatic** [comment]
Closing for now, until we get the better picture of the documentation needs.
