### ISSUE TITLE
installation instructions and requirements are confusing/misleading

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#15]
There are a few things that are confusing:

1. PEX is framed as just a mac installation method. However it also works on linux.
2. PIP is framed as an 'advanced' installation method and contains the phrase "Once Kolibri is released". There's no indication that it works on Mac, Windows, and Linux
3. The linux system requirements are very confusing
   * There are three independent-looking items, Ubuntu, Debian/Raspbian, and Linux. However these are not mutually exclusive categores (Linux > Debian > Ubuntu). This is leading to [confusion like this](https://github.com/learningequality/kolibri-installer-debian/issues/25)
   * The Debian support is much more limited than PEX and PIP support, and this isn't indicated. Sounds like it's currently only Python 3.4 and 3.5? ([see also this](https://github.com/learningequality/kolibri-installer-debian/issues/29))

Seems like we might need to better distinguish installation _methods_ (pip, .deb, pex, etc) from install targets (debian linux variants, osx, general linux, etc).

cc @radinamatic  @benjaoming

**Comment by radinamatic** [comment]
Good points @indirectlylit, I'll think about best way to rework the system requirements and installation pages for Linux and Mac.

**Comment by benjaoming** [comment]
Fixed in #16
