### ISSUE TITLE
Troubleshooting: Malformed Database can also happen on other SQLite db files

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-docs#153]
Pending a possibly automatic resolution of "malformed database" occurring for `~/.kolibri/job_storage.sqlite3` and `~/.kolibri/process_cache/cache.db`, we should perhaps expand our Troubleshooting section here:

https://kolibri.readthedocs.io/en/latest/manage/get_support.html#troubleshoot-database-issues

The resolution for the other files is to simply delete them entirely and start Kolibri again, as they should be automatically created.

**Comment by radinamatic** [comment]
Fixed in #157, closing.
