### ISSUE TITLE
Malformed DB guidance

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri-docs#162]
I was following the instructions provided here: https://kolibri.readthedocs.io/en/latest/manage/get_support.html#troubleshoot-database-issues

but wasn't successful as I was trying to fix a malformed db. Instead I got returned a fix db that was empty.

@rtibbles and @lyw07 helped me debug, ran this command instead:
`sqlite3 corrupted_db_name .recover | sqlite3 fixed.db`

`.recover` was introduced last year in version 3.29: https://sqlite.org/changes.html

Request: It would be good to add .recover to the docs, but with the version caveat.

**Comment by benjaoming** [comment]
Thanks for the report @jeepurs 

> Instead I got returned a fix db that was empty.

Was this because of a mistake in the docs that can be fixed? Do you remember how it happened? People aren't supposed to end up with empty databases for sure! :)

**Comment by rtibbles** [comment]
@benjaoming I think it's just that our guidance only works for some classes of malformed DBs - the SQLite `.recover` command is much better at this as it will work past errors to recover as much data as possible.

**Comment by radinamatic** [comment]
@rtibbles Should we forgo the previous steps in our docs and recommend only the use of the `recover` command?

**Comment by benjaoming** [comment]
@radinamatic no, SQLite3 is in version 3.22 on Ubuntu 18.04
