### ISSUE TITLE
travis warnings might not be reproducible locally?

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#17]
An earlier version of #16 had some travis errors: https://github.com/learningequality/kolibri-docs/pull/16#issuecomment-383793642

However @radinamatic had difficulty reproducing locally:

![image](https://user-images.githubusercontent.com/2367265/39216371-3d480aa0-47d0-11e8-800d-fce25ccc882d.png)

This issue is a placeholder to look into this, and if necessary document how to get errors & warnings to show up when editing docs locally...

cc @benjaoming if you happen to know offhand?

**Comment by benjaoming** [comment]
@radinamatic how do you build docs? `make docs` ?

**Comment by radinamatic** [comment]
I run `sphinx-autobuild` command from the `docs` folder, so it updates on every change.

Anyways, I can at least see *some* errors locally, so not sure if the issue has been resolved in the meantime...

**Comment by benjaoming** [comment]
It's best to run the same commands as Travis, `make docs` will build on a cleaned base, while `sphinx-autobuild` could theoretically do something causing warnings on top of an unclean build.

Let's close it -- reopen again with specific warning messages uncaught, then we can look into it :)

**Comment by radinamatic** [comment]
Noted, I will run a `make docs` prior to committing! 👍

**Comment by radinamatic** [comment]
Example of error not caught by `sphinx-autobuild`, only `make docs`:

![screenshot - 04-jun-18 4_32_00 pm](https://user-images.githubusercontent.com/1457929/40924260-15de062e-6817-11e8-8046-80722cf0bdda.png)


```
(kolibri-docs) didivm@didivm-VirtualBox:~/LE/kolibri-docs/docs$ sphinx-autobuild --port 8888 . _build

+--------- manually triggered build ---------------------------------------------
| Running Sphinx v1.7.2
| loading pickled environment... done
| building [mo]: targets for 0 po files that are out of date
| building [html]: targets for 0 source files that are out of date
| updating environment: 0 added, 0 changed, 0 removed
| looking for now-outdated files... none found
| no targets are out of date.
| build succeeded.
| 
| The HTML pages are in _build.
+--------------------------------------------------------------------------------

[I 180604 00:33:26 server:283] Serving on http://127.0.0.1:8888
[I 180604 00:33:26 handlers:60] Start watching changes
[I 180604 00:33:26 handlers:62] Start detecting changes
[I 180604 00:33:32 handlers:133] Browser Connected: http://127.0.0.1:8888/coach.html#
^C[I 180604 07:13:55 server:303] Shutting down...
(kolibri-docs) didivm@didivm-VirtualBox:~/LE/kolibri-docs/docs$ cd ..
(kolibri-docs) didivm@didivm-VirtualBox:~/LE/kolibri-docs$ make docs
make -C docs clean
make[1]: Entering directory '/home/didivm/LE/kolibri-docs/docs'
rm -rf _build/*
make[1]: Leaving directory '/home/didivm/LE/kolibri-docs/docs'
make -C docs html
make[1]: Entering directory '/home/didivm/LE/kolibri-docs/docs'
sphinx-build -b html -W -d _build/doctrees   . _build/html
Running Sphinx v1.7.2
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 8 source files that are out of date
updating environment: 8 added, 0 changed, 0 removed
reading sources... [100%] manage                                                                                                     

Warning, treated as error:
manage/_content.rst:95:Undefined substitution referenced: "lock-open".
Makefile:53: recipe for target 'html' failed
make[1]: *** [html] Error 2
make[1]: Leaving directory '/home/didivm/LE/kolibri-docs/docs'
Makefile:35: recipe for target 'docs' failed
make: *** [docs] Error 2
(kolibri-docs) didivm@didivm-VirtualBox:~/LE/kolibri-docs$ 
``

**Comment by benjaoming** [comment]
@radinamatic yes, is there a way to have this `Warning, treated as error` enabled for autodocs? Maybe there are some docs about that :smile:

**Comment by radinamatic** [comment]
There probably are, will investigate! 😉
