### ISSUE TITLE
Expand uninstallation guide

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-docs#176]
Uninstall steps, for instance for the Mac, could be improved by adding steps to remove user data. For instance:

> Removing all data
>
> In order to delete the user data of Kolibri and start over from scratch, locate the `.kolibri` folder that contains the Kolibri database and delete the entire folder. The folder's location is displayed in [Device Info](https://kolibri.readthedocs.io/en/latest/manage/device_info.html).

https://kolibri.readthedocs.io/en/latest/install/macos.html#uninstall

Here is an example of a user that wants to start over in order to get the installation Wizard again: https://community.learningequality.org/t/support-in-creating-a-new-superadmin-account/1534

**Comment by indirectlylit** [comment]
agreed.

Note we mention this in the Pex instructions, but it actually has a typo (`./kolibri` rather than `~/.kolibri`): https://kolibri.readthedocs.io/en/latest/install/python.html?highlight=home#uninstall-pex

> ![image](https://user-images.githubusercontent.com/2367265/83577823-0a47c680-a4ea-11ea-8644-9f4f8a6fa7e9.png)

**Comment by radinamatic** [comment]
Fixed in #179, closing.
