### ISSUE TITLE
duplicate configuration files

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#19]
I see two copies of a few files:

* Makefile [1](https://github.com/learningequality/kolibri-docs/blob/develop/Makefile) [2](https://github.com/learningequality/kolibri-docs/blob/develop/docs/Makefile)
* conf.py [1](https://github.com/learningequality/kolibri-docs/blob/develop/conf.py) [2](https://github.com/learningequality/kolibri-docs/blob/develop/docs/conf.py)
* crowdin.yaml [1](https://github.com/learningequality/kolibri-docs/blob/develop/crowdin.yaml) [2](https://github.com/learningequality/kolibri-docs/blob/develop/docs/crowdin.yaml)

noticed while reviewing #18

-----

cc @radinamatic @benjaoming

**Comment by benjaoming** [comment]
@indirectlylit the `Makefile` is different, the two others are indeed a mistake, thanks for spotting!
