### ISSUE TITLE
Import Content Not working

### ISSUE THREAD

**Issue by cts-prog3** [learningequality/kolibri-docs#20]
I have installed Kolibri locally on a Windows 7 desktop with internet connection.  When I try to import content it shows a list of 22 channels but when I choose Khan Academy it just says "Generating channel listing. This could take a few minutes…" and has been for a few hours now.  Any ideas on how to import Khan Academy?

**Comment by indirectlylit** [comment]
Hi, thanks for trying Kolibri!

Generating the channel listing should not take hours, even for Khan Academy which is a very, very large channel.

* What version of Kolibri are you using?
* Do you see any errors in any log files in `C:/Users/<your_username>/.kolibri/`?

----

FYI, you can ask support questions in our community forums here: http://community.learningequality.org/

**Comment by cts-prog3** [comment]
Now it seems to be working.  Any plan on adding more Khan Academy content in the future?

**Comment by indirectlylit** [comment]
> Now it seems to be working

Glad to hear!

> Any plan on adding more Khan Academy content in the future?

I'd recommend asking that question in the [Content and Materials](http://community.learningequality.org/c/content-materials) section of the community forums
