### ISSUE TITLE
Add documentation for adding routes in Kolibri

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri-docs#227]
Should include the necessary steps including:
- adding to `constants.js`
- adding to `handlers.js` (if necessary)
- adding to the appropriate `route.js`

**Comment by radinamatic** [comment]
@sairina This sounds like a dev docs issue/need, correct? 
If that's the case, it should be opened in the `kolibri` repo, as this one is for end-user-facing documentation. 🙂

**Comment by sairina** [comment]
Ahh. You're right, and that makes sense! All right, closing this and adding this one in the `kolibri` repo. Thanks for catching that!

**Comment by indirectlylit** [comment]
FYI for future reference, Github has a 'Transfer issue' feature:

https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository
