### ISSUE TITLE
Improve the PDF output from ReadTheDocs platform

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-docs#23]
Current [default PDF output from the RTD](https://media.readthedocs.org/pdf/kolibri/latest/kolibri.pdf) version of the docs is not optimal and it can use several improvements.

- better text & page formatting
- consistency in image sizes
- accessibility

**Comment by ivanistheone** [comment]
Let me know if I can help with something on that front. I've got 10+ years experience with LaTeX ;)

**Comment by radinamatic** [comment]
That would be awesome, thanks @ivanistheone! :pray:

**Comment by radinamatic** [comment]
Fixed in #78 & 81, closing!
