### ISSUE TITLE
tip in content management section is phrased oddly

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#24]
![image](https://user-images.githubusercontent.com/2367265/40555133-f98cbd7a-5ffc-11e8-99de-972e2ae68d44.png)

The parenthetic phrase "navigate away or manage users" sounds self-contradictory.

Maybe it should be "view learner content or manage users"?

**Comment by radinamatic** [comment]
Agreed, it could be formulated better! :+1: 
I'm in the middle of another small improvement, will include this too!

**Comment by indirectlylit** [comment]
thank you!
