### ISSUE TITLE
New installation method for Debian and Ubuntu

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri-docs#241]
For security reasons, beginning in Debian 12 and Ubuntu 22.04, `apt-key` will trigger a deprecation message. The current installation methods explained in the docs will be deprecated in the future.
The new method, valid both for Debian and Ubuntu is this one:
```
sudo gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys DC5BAA93F9E4AE4F0411F97C74F88ADB3194DD81
sudo gpg --output /usr/share/keyrings/learningequality-kolibri.gpg --export  DC5BAA93F9E4AE4F0411F97C74F88ADB3194DD81

sudo su -c 'echo "deb [signed-by=/usr/share/keyrings/learningequality-kolibri.gpg] http://ppa.launchpad.net/learningequality/kolibri/ubuntu jammy main" > /etc/apt/sources.list.d/learningequality-ubuntu-kolibri.list'

sudo apt-get update
sudo apt install kolibri
```

Docs at https://kolibri.readthedocs.io/en/latest/install/ubuntu-debian.html must reflect this change for these versions of Debian & Ubuntu and considered deprecated the previous methods , to be used only in old versions of these distributions.

Relates: https://github.com/learningequality/kolibri-installer-debian/issues/114

**Comment by holta** [comment]
Thanks to @jredrejo's original recommendation 2022-08-31:

- https://github.com/iiab/iiab/issues/3343#issuecomment-1233163573

Great to see this is being mainlined for more reliable operations across Debian-like OS's in 2023 👍
