### ISSUE TITLE
add a 'Server URL' sub-heading to 'Access Kolibri' section

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#30]
Currently, information about finding the URL (IP+ port) of the server is under the _[Compatibility](https://github.com/learningequality/kolibri-docs/blob/develop/docs/access.rst#compatibility)_ section of _[Accessing Kolibri from Other Devices in the Network](https://github.com/learningequality/kolibri-docs/blob/develop/docs/access.rst#accessing-kolibri-from-other-devices-in-the-network)_ 

Recommend adding a new sub-section header at the same level as _Compatibility_ called _Server URL_ or similar.

**Comment by radinamatic** [comment]
@indirectlylit 

The sub-section heading [Setup Access on Other Devices](https://kolibri.readthedocs.io/en/latest/access.html#setup-access-on-other-devices) covers the topic of finding the server URL, and it _is_ at the same level as _Compatibility_.  

Do you suggest to change the heading from _Setup Access on Other Devices_ to _Server URL_? I don't have strong opinions, and can make the change if you think it's better.

![access kolibri kolibri 0 10 x documentation - mozilla firefox_108](https://user-images.githubusercontent.com/1457929/47599016-9e17ef00-d9a5-11e8-9af0-c6ec86f1f0a1.png)

**Comment by indirectlylit** [comment]
It looks like you added the 'Setup Access on Other Devices' header 12 days after I filed this issue in a5f18149caaa06fa8e4dda17b4d5b08e925cdab0 :)

looks good to me!

**Comment by radinamatic** [comment]
My bad then for not closing the issue back than... :woman_facepalming:

**Comment by indirectlylit** [comment]
it may have been a coincidence!

**Comment by indirectlylit** [comment]
filed a related issue on 'setup' vs 'set up' - #55
