### ISSUE TITLE
raspberry pi instructions outdated

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#33]
* [x] still references the `kolibri` user: https://github.com/learningequality/kolibri-docs/pull/32/files#diff-d3596120b107503957511384889d9a08R40

cc @benjaoming @radinamatic 

* [x] Also, we now have the 'change content directory' command. We should probably update the instructions to use that?

**Comment by indirectlylit** [comment]
Also, this line is no longer true:

>  Loading channels can take a **long time** on a Raspberry Pi. When generating channel contens for Khan Academy, the step indicated as "Generating channel listing. This could take a few minutes…" could mean ~30 minutes

**Comment by benjaoming** [comment]
True that! Thanks for finding this!

**Comment by radinamatic** [comment]
Yes, the latest RPi improvements were added *after* we reviewed the RPi docs section last week... 🤦‍♀️

**Comment by indirectlylit** [comment]
the inexorable march of progress!

**Comment by indirectlylit** [comment]
While doing some basic rpi load testing today, we noticed that loading of exercises was slow.

As @jamalex said:

> One thing we didn't do in this setup (and not sure whether we recommend in our docs for the Pi) is put nginx in front of Kolibri to serve up static assets and help handle heavier concurrency

Also from @rtibbles:

> the zip endpoint loading seems to be a bottleneck, judging from the exercise data and image loading slow downs. So, adding nginx on the RPi would be important for helping with that under load

Sounds like it would be smart to include nginx instructions for rpi

**Comment by benjaoming** [comment]
@indirectlylit this will be handled in a separate Debian package, AFAIK. Putting effort into making people do this through their own configurations would be a very temporary solution and would require to somehow tell people to revert those changes once that package arrives.

**Comment by indirectlylit** [comment]
That's fair. Then maybe we should just add a note for advanced users? E.g. something like:

> Note that low-power devices like the Pi will not currently handle more than about 15 concurrent users. This performance will increase in future releases as we make optimizations and provide options to run Kolibri behind nginx. Advanced users may wish to experiment with setting up nginx themselves; however please be aware that we cannot provide support for this configuration and it may cause conflicts with a future update.

**Comment by benjaoming** [comment]
That's a good note - will include that :)

**Comment by indirectlylit** [comment]
Another recommendation reported here: https://github.com/learningequality/kolibri/issues/4040

When pip-installing on a Pi, use `--no-cache-dir` to prevent `MemoryError`s

**Comment by benjaoming** [comment]
Needed for clarification and explicity in docs: We should do everything according to the packages on Raspbian Jessie/Stretch **Lite**.

Raspbian Jessie vs Raspbian Stretch should be totally explicit, if the instructions are not overlapping.

Jessie Lite observations -- these are necessary in addition to current instructions:

 * `apt install python3-pip` is necessary
 * `apt install python3-pkg-resources` is necessary (pre-depends!)
 * `pip3 install setuptools --upgrade` - for `pkg_resources` to work with local builds with version strings like `1.2.3+git.123.1234abcde`

After all this, I have Kolibri `0.11.0a5.dev0+git.315.g18324898` running on Raspbian Jessie w/o issues.

**Comment by benjaoming** [comment]
Further notes:

 * Let's move the `cffi` installation as a prerequisite, it's strange to have this "after installation, Kolibri will not start..."
 * Raspberry Pi drive I/O is slow and USB ports are 2.0. Often, the SD card reader has speeds around 30-80 MB/sec, the USB interface reaches comparable speeds. I think it's worth mentioning somewhere. Maybe we should kick off a background section with some considerations / recommendations.

**Comment by indirectlylit** [comment]
Another important issue:

 * [x] The docs still say that in the case of running out of space, you should set up symbolic links between your Kolibri home folder and an external drive.

This is [causing confusion](https://github.com/learningequality/kolibri/issues/4227#issuecomment-426831343) because it contradicts our guidance to use the new `content movedirectory` command for this purpose.

**Comment by benjaoming** [comment]
Good point, I'll make sure that `kolibri manage content movedirectory` is mentioned firstly.

**Comment by benjaoming** [comment]
All feedback from this issue addressed in #51
