### ISSUE TITLE
add information about channel versions and updating

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#57]
The [manage content](https://kolibri.readthedocs.io/en/latest/manage.html#manage-content) docs currently describe how to import new content from an existing channel, but don't describe how to update the version of existing content.

It's a slightly subtle difference, and we had a [question about how to do it in the forums](http://community.learningequality.org/t/missing-images-graphs-questions/911/2).

We should probably also describe how channels are versioned, because this comes up a lot with KA.

**Comment by ivanistheone** [comment]
Related video tutorial on this topic from the "Everything about Kolibri" channel:
http://35.196.115.213/learn/#/topics/c/7916afd91c60593eb2dc383b338df42f

**Comment by radinamatic** [comment]
Fixed in #106, closing!
