### ISSUE TITLE
Add a note about ChromeOS

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-docs#58]
Perhaps change the PPA instructions to recommend using a different method (RPi) for ChromeOS.

**Comment by jredrejo** [comment]
I think the PPA finally worked after installing gpg in the Chromebook. The problem now is that the chromebook is firewalling the Linux services.
Using RPi instructions will face the same problem.

**Comment by benjaoming** [comment]
Oh yeah, didn't see that the poster [in forums](http://community.learningequality.org/t/apt-get-install-on-chomebook-linux/917/7) actually made it work

> I can install Kolibri from the .deb package and it will run on that machine

Maybe it's a bit beyond our scope to write docs about firmware modifications om Chromebooks :)
