### ISSUE TITLE
ubuntu instructions say that python 3.7+ is not supported

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#72]
https://kolibri.readthedocs.io/en/latest/install.html#id3

![image](https://user-images.githubusercontent.com/2367265/54953381-57530480-4f05-11e9-8871-da913660734a.png)

Python 3.7 support was added in https://github.com/learningequality/kolibri-installer-debian/pull/55

----

cc @radinamatic

**Comment by radinamatic** [comment]
Gotcha, will correct this week! 👍

**Comment by radinamatic** [comment]
Fixed in #73
