### ISSUE TITLE
[Docs] Kolibri Server Configuration 

### ISSUE THREAD

**Issue by arky** [learningequality/kolibri-docs#79]
Please kindly add some documentation on settings of your kolibri server package using the various configuration files in /etc/default /etc/kolibri etc.

This information is useful for installations on Gnu/Linux distributions and also on ARM based devices like Raspberry Pi.

**Comment by radinamatic** [comment]
Hi @arky!

Thank you for testing Kolibri and `kolibri-server`! Early tester's contributions like yours are very much appreciated and can help us catch issues and fine-tune the performance.

`kolibri-server` package is still in development, and has not yet been formally released. At the time we finally program its release, we will certainly add all the necessary documentation, so the users are aware of all the features, configuration options, and the installation procedure.
