### ISSUE TITLE
Recommend Simpler Captive Portal default domain 'kolibri.library' 

### ISSUE THREAD

**Issue by arky** [learningequality/kolibri-docs#80]
In my deployment I found that typing 'http://kolibri.library' was too long and difficult for non-native speakers on tiny mobile keyboards. I reverted to using simpler 'http://box/' 'http://box.lan' naming scheme for my Kolibri deployments. 

This is much easier for our users. Both 'Kolibri' and 'library' have prone to mis-spellings. Also OpenWRT by default recommends using '.lan' domain for its local domains, instead of '.local' to avoid conflict with ZeroConf. 

Of course, as a fallback I have standard captive portal dns redirects in place. Hope this feedback would make the kolibri docs better!

**Comment by indirectlylit** [comment]
thanks for the note!

@radinamatic @jredrejo customizing the host name was mentioned in the raspberry pi page: https://kolibri.readthedocs.io/en/latest/install/tutorials/rpi.html#installing-kolibri

**Comment by radinamatic** [comment]
Closed in #87
