### ISSUE TITLE
Link shows 404

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri-docs#83]
`https://github.com/learningequality/kolibri/blob/develop/CHANGELOG.rst` currently shows a 404 -- this link is provided in the RTD documentation.

![image](https://user-images.githubusercontent.com/5150483/56907683-a1299000-6a59-11e9-8b0c-9cc3a3e6764e.png)

**Comment by jeepurs** [comment]
`https://github.com/learningequality/kolibri-docs/blob/origin/release-v0.12.x/docs/index.rst` also shows a 404.  This is linked in the top right corner: 
![image](https://user-images.githubusercontent.com/5150483/56907593-70495b00-6a59-11e9-8771-fc620df4f1b2.png)

**Comment by jonboiser** [comment]
The .rst version of the changelog does not appear to be in the repository anymore. 

We should have the link point to the .md version.

**Comment by radinamatic** [comment]
Thanks for investigating @jonboiser, will correct asap!

**Comment by indirectlylit** [comment]
ref: #86

**Comment by radinamatic** [comment]
Not strictly a docs issue, as the link used on that page was pointing to a redirect  https://learningequality.org/r/kolibri-changes. 

I've corrected the URL in the redirect rule, and now links from both the `latest` and the `release-v0.12.x` version of the docs are not dead anymore :slightly_smiling_face:.
