### ISSUE TITLE
user confused by command line instructions

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#85]
In the instructions, we say 

> To export Kolibri content channels on a local drive in order to share it with another device, run these two commands in sequence. The first exports the channel database, and the second exports the resources (videos, documents, etc.).
> 
> ```
> kolibri manage exportchannel -- <Channel ID> /path/to/local/drive/KOLIBRI_DATA
> kolibri manage exportcontent -- <Channel ID> /mount/mydrive/KOLIBRI_DATA
> ```
> 
> The path should be to a folder named `KOLIBRI_DATA` at the root of the local drive, so it will get picked up later for importing via the Web UI.

One user thought they were supposed to keep the `<` `>` and tried

```
kolibri manage exportchannel -- <ec164fee25ee526296e68f71e169> /Volumes/mydrive/KOLIBRI_DATA

**Comment by indirectlylit** [comment]
cc @radinamatic

**Comment by rtibbles** [comment]
Also, the fact that the file paths are different for each command, when they should in fact be the same to export one channel to the same location is a bit confusing.

**Comment by radinamatic** [comment]
> One user thought they were supposed to keep the `< >`

We do state the instructions at the beginning of the section:

`In the commands below, angle brackets and the text between them <...> are used to denote placeholders for you to modify. Make sure to replace them with your own information.`

I'll reformat it as a `Warning` note, to increase the chance of it to be read.

>  file paths are different for each command, when they should in fact be the same to export one channel to the same location is a bit confusing

Agreed, will amend!

**Comment by radinamatic** [comment]
Fixed in #87

**Comment by benjaoming** [comment]
> We do state the instructions at the beginning of the section:

Haha yes, and I think it's reasonable to require that users actually read the instructions. Eventually placing everything in Warning box doesn't scale :smile: 

I think another easy solution would be to add harmless examples. E.g.

> Here's an example where a Channel ID is inserted:
> ```
> kolibri manage exportchannel -- afed7aef6e8da7efed9e7ef02 /path/to/local/drive/KOLIBRI_DATA
> ```

(we can probably make better use of examples in more complex cases)

If we can stick to consistently using `<placeholder>` that's great, are there any changes here?

**Comment by radinamatic** [comment]
Added some examples in the 0.12.4 update, thanks for the tip!

> If we can stick to consistently using \<placeholder\> that's great, are there any changes here?

I believe it has been consistent so far, let me know if you find where it was missed.
