### ISSUE TITLE
add dead link checker

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#86]
similar to issue in kolibri dev docs: https://github.com/learningequality/kolibri/issues/5146

**Comment by radinamatic** [comment]
@indirectlylit Wasn't this supposed to perform the link check?
https://github.com/learningequality/kolibri-docs/blob/develop/docs/Makefile#L158

**Comment by indirectlylit** [comment]
yes, good find! Seems like it must not be part of our build / CI processes

**Comment by radinamatic** [comment]
Well, it certainly works on `kolibri-docs` build/CI (gave me so many headaches during the first 0.12 updates PR until @benjaoming helped me figure out what I was missing  :unamused: :woman_facepalming:), so I'm going to close this issue.

I can't figure out why it isn't working on the dev docs, as the `Makefile` is virtually identical, a part from dev docs one missing the i18n options at the end... :confused:

**Comment by benjaoming** [comment]
I've added a weekly job on Travis CI for the `develop` branch, so we catch 404s even though we aren't opening any PRs.

**Comment by indirectlylit** [comment]
How does that work in practice as far as notifications to the team?

Would this item have been caught? https://github.com/learningequality/kolibri-docs/issues/83
