### ISSUE TITLE
Move RPI instructions to tutorial

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-docs#94]
The current instructions for Debian/Ubuntu are better off if we put the RPI-specific instructions directly in the tutorial and maintain them as RPI-specific instructions.

Continuation of https://github.com/learningequality/kolibri-docs/pull/87

**Comment by indirectlylit** [comment]
this appears to be completed

![image](https://user-images.githubusercontent.com/2367265/59638409-63c2b400-9126-11e9-9db8-3dd001df7d6a.png)
