### ISSUE TITLE
ensure documented android browser support is accurate

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#95]
Currently [we list Android browser support](https://kolibri.readthedocs.io/en/latest/access.html#compatibility) as being "Android 4.2+: Chrome and Firefox"

Is this accurate? At one point, I believe we were aiming to support the stock browser down to 4.0. cc @rtibbles do we have any information on whether this is still actually a requirement?

ref: renewed discussion about the use of flexbox in Kolibri, which we've avoided until now https://github.com/learningequality/kolibri/pull/5475

**Comment by rtibbles** [comment]
We were aiming to support down to 4.0.4 - my instinct is that this is no longer a hard requirement, but I don't have any data to make this claim one way or another.

**Comment by indirectlylit** [comment]
@mrpau-dev @radinamatic do you guys know if older stock browsers are in our integration test suite?

**Comment by radinamatic** [comment]
The oldest Android device I have to test runs the version 4.4.4, and Kolibri apparently works well in both Firefox and Chrome. 

During the testing on Browserstack, I did not manage to open Kolibri in any of the emulators lower than 4.4. I'll amend the documentation to reflect this.
